files:
  - source: /Resources/Private/Language/locallang*.xlf
    translation: /Resources/Private/Language/%locale_with_underscore%.%original_file_name%

  - source: /Configuration/Sets/FeedDisplay/labels.xlf
    translation: /Configuration/Sets/FeedDisplay/%locale_with_underscore%.%original_file_name%
