categories:
  feeddisplay: ~
  feeddisplay.templates:
    parent: feeddisplay
  feeddisplay.general:
    parent: feeddisplay
  feeddisplay.advanced:
    parent: feeddisplay
  feeddisplay.getFields:
    parent: feeddisplay

settings:
  plugin.tx_feeddisplay_pi1.view.templateRootPath:
    type: string
    default: ''
    category: feeddisplay.templates
  plugin.tx_feeddisplay_pi1.view.partialRootPath:
    type: string
    default: ''
    category: feeddisplay.templates
  plugin.tx_feeddisplay_pi1.view.layoutRootPath:
    type: string
    default: ''
    category: feeddisplay.templates
  plugin.tx_feeddisplay_pi1.settings.ignoreFlexFormSettingsIfEmpty:
    type: string
    default: 'feedUrl,maxFeedCount,maxContentLength,maxHeaderLength,logoMaxWidth,logoMaxHeight,feedIconMaxWidth,feedIconMaxHeight,dateFormat,stripTags,linkTarget,errorMessage,cacheDuration,getFields.feed,getFields.items'
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.feedUrl:
    type: string
    default: https://typo3.org/rss
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.maxFeedCount:
    type: int
    default: 10
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.maxContentLength:
    type: int
    default: 500
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.maxHeaderLength:
    type: int
    default: 80
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.logoMaxWidth:
    type: int
    default: 0
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.logoMaxHeight:
    type: int
    default: 0
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.feedIconMaxWidth:
    type: int
    default: 26
    category: feeddisplay.general
  plugin.tx_feeddisplay_pi1.settings.feedIconMaxHeight:
    type: int
    default: 26
    category: feeddisplay.advanced
  plugin.tx_feeddisplay_pi1.settings.dateFormat:
    type: string
    default: '%d. %B %Y'
    category: feeddisplay.advanced
  plugin.tx_feeddisplay_pi1.settings.stripTags:
    type: int
    default: 1
    category: feeddisplay.advanced
  plugin.tx_feeddisplay_pi1.settings.linkTarget:
    type: string
    default: '_blank'
    category: feeddisplay.advanced
  plugin.tx_feeddisplay_pi1.settings.errorMessage:
    type: string
    default: ''
    category: feeddisplay.advanced
  plugin.tx_feeddisplay_pi1.settings.cacheDuration:
    type: int
    default: 3600
    category: feeddisplay.advanced
  plugin.tx_feeddisplay_pi1.settings.getFields.feed:
    type: string
    default: 'author,authors,contributor,contributors,copyright,description,encoding,favicon,items,item_quantity,language,link,links,permalink,title,type,subscribe_url,latitude,longitude,image_height,image_link,image_title,image_url,image_width,all_discovered_feeds,base'
    category: feeddisplay.getFields
  plugin.tx_feeddisplay_pi1.settings.getFields.items:
    type: string
    default: 'author,authors,categories,category,content,contributor,contributors,copyright,date|U,description,enclosure,enclosures,feed,id,link,links,local_date|,permalink,source,title,latitude,longitude,base'
    category: feeddisplay.getFields
